name: BESS
channels:
  - defaults
dependencies:
  - pip
  - pypsa>=0.18
  - atlite
  - yaml
  - numpy
  - pandas
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely
  - pyomo
  - matplotlib
  - flask
  - redis-py
  - rq
  - ipython
prefix: /home/noego/anaconda3/envs/BESS



