name: bess
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.10.5=h4c7d964_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - coincbc
  - coin-or-cbc=2.10.12=hd3ed8bd_4
  - coin-or-cgl=0.60.9=hacf86d0_6
  - coin-or-clp=1.17.10=h626fd10_3
  - coin-or-osi=0.108.11=h5b68f48_7
  - coin-or-utils=2.11.12=hdb10741_6
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.13.7=py313hd8ed1ab_100
  - debugpy=1.8.17=py313h927ade5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - krb5=1.21.3=hdf4eb48_0
  - libblas=3.9.0=35_h5709861_mkl
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.4=hf5d6505_0
  - libxml2=2.15.0=ha29bfb0_1
  - libxml2-16=2.15.0=h06f855e_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.2=hfa2b4ca_3
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2024.2.2=h57928b3_16
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh145f28c_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py313h5ea7bf4_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.13.7=hdf00ec1_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.7=h4df99d1_100
  - python_abi=3.13=8_cp313
  - pywin32=311=py313h40c08fc_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.13.0=h18a62a1_3
  - tk=8.6.13=h2c6b04d_2
  - tornado=6.5.2=py313h5ea7bf4_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - pip:
      - affine==2.4.0
      - altair==5.5.0
      - appdirs==1.4.4
      - argparse-dataclass==2.0.0
      - atlite==0.4.1
      - attrs==25.3.0
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - bottleneck==1.6.0
      - cachetools==6.2.0
      - cdsapi==0.7.7
      - certifi==2025.8.3
      - cffi==2.0.0
      - cfgrib==0.9.15.1
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.3
      - click==8.3.0
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - conda-inject==1.3.2
      - configargparse==1.7.1
      - connection-pool==0.0.3
      - contourpy==1.3.3
      - country-converter==1.3.1
      - cycler==0.12.1
      - dask==2025.9.1
      - deprecation==2.1.0
      - docutils==0.22.2
      - dpath==2.2.0
      - eccodes==2.43.0
      - ecmwf-datastores-client==0.4.0
      - entsoe-py==0.7.4
      - et-xmlfile==2.0.0
      - fastjsonschema==2.21.2
      - findlibs==0.1.2
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - geographiclib==2.1
      - geopandas==1.1.1
      - geopy==2.4.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.25.1
      - google-auth==2.41.1
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.4.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - gurobipy==12.0.3
      - h5netcdf==1.6.4
      - h5py==3.14.0
      - highspy==1.11.0
      - humanfriendly==10.0
      - idna==3.10
      - immutables==0.21
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - linopy==0.5.7
      - locket==1.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - multiurl==0.3.7
      - narwhals==2.6.0
      - nbformat==5.10.4
      - netcdf4==1.7.2
      - networkx==3.5
      - numexpr==2.13.1
      - numpy==2.3.3
      - openpyxl==3.1.5
      - pandas==2.3.3
      - partd==1.4.2
      - pillow==11.3.0
      - plotly==6.3.0
      - polars==1.33.1
      - powerplantmatching==0.7.1
      - progressbar2==4.5.0
      - proto-plus==1.26.1
      - protobuf==6.32.1
      - pulp==3.3.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycountry==24.6.1
      - pycparser==2.23
      - pydeck==0.9.1
      - pyogrio==0.11.1
      - pyparsing==3.2.5
      - pyproj==3.7.2
      - pypsa==0.35.2
      - pyreadline3==3.5.4
      - python-utils==3.9.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - rasterio==1.4.3
      - referencing==0.36.2
      - requests==2.32.5
      - reretry==0.11.8
      - rpds-py==0.27.1
      - rsa==4.9.1
      - scipy==1.16.2
      - seaborn==0.13.2
      - shapely==2.0.7
      - smart-open==7.3.1
      - smmap==5.0.2
      - snakemake==9.11.7
      - snakemake-interface-common==1.22.0
      - snakemake-interface-executor-plugins==9.3.9
      - snakemake-interface-logger-plugins==2.0.0
      - snakemake-interface-report-plugins==1.2.0
      - snakemake-interface-scheduler-plugins==2.0.1
      - snakemake-interface-storage-plugins==4.2.3
      - soupsieve==2.8
      - streamlit==1.51.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - throttler==1.2.2
      - toml==0.10.2
      - toolz==1.0.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - unidecode==1.4.0
      - urllib3==2.5.0
      - validators==0.35.0
      - watchdog==6.0.0
      - wrapt==1.17.3
      - xarray==2025.9.1
      - xlrd==2.0.2
      - yte==1.9.0
prefix: C:\Users\noego\AppData\Local\spyder-6\envs\bess

